#!/usr/bin/python

import subprocess, sys, os

Environment = raw_input('Enter Environment Name > ')
wholeORrange = raw_input('Do you want to implement this change for the whole environment (type whole) or Do you want to implement this change to just an specific range (type range) > ')
Directory = "/etc/HPCCSystems/nagios/%s" % Environment
Check_Command = raw_input('Enter check_command to remove > ')

### Deleting entry in host configuration file

if wholeORrange == "range":
        IPRange = raw_input('Enter IP range i.e. 10.241.30.1-200 > ')

	def DeleteRangeEntry():
		ClusterRange = IPRange.split('.')[-1]
                firstNumber = int(ClusterRange.split('-')[0])
                secondNumber = int(ClusterRange.split('-')[1])
                for ip in range(firstNumber, secondNumber):
                        FullName =  IPRange.split('.')[0] + '.' + IPRange.split('.')[1] + '.' + IPRange.split('.')[2] + '.' + str(ip) + '.' + "cfg"
                        for filename in os.listdir(Directory):
                                if filename == FullName:
					cmd = "awk -v RS= '!/%s/{printf $0\"\\n\"}' /etc/HPCCSystems/nagios/%s/%s" % (Check_Command, Environment, filename) 
					new_conf = os.popen(cmd).read()
					absolute_path = Directory + '/' + filename
					config_file = open(absolute_path, 'w')
					config_file.write(new_conf)
					config_file.close()
					cmd_sed = "sed -i \"s/}/}\\n/g\" /etc/HPCCSystems/nagios/%s/%s" % (Environment, filename)
					os.popen(cmd_sed).read()

	DeleteRangeEntry()

### Changing file ownership

	subprocess.call('chown nagios. /etc/HPCCSystems/nagios/ -R', shell=True)

### Restarting Nagios application

        subprocess.call('/etc/init.d/nagios restart', shell=True)

elif wholeORrange == "whole":

	def DeleteEntry():
		for filename in os.listdir(Directory):
			cmd = "awk -v RS= '!/%s/{printf $0\"\\n\"}' /etc/HPCCSystems/nagios/%s/%s" % (Check_Command, Environment, filename) 
			new_conf = os.popen(cmd).read()
			absolute_path = Directory + '/' + filename
			config_file = open(absolute_path, 'w')
			config_file.write(new_conf)
			config_file.close()
			cmd_sed = "sed -i \"s/}/}\\n/g\" /etc/HPCCSystems/nagios/%s/%s" % (Environment, filename)
			os.popen(cmd_sed).read()
	DeleteEntry()

### Changing file ownership

	subprocess.call('chown nagios. /etc/HPCCSystems/nagios/ -R', shell=True)

### Restarting Nagios application

        subprocess.call('/etc/init.d/nagios restart', shell=True)

else:

        print "ScriptKiddie or most likely USER (meaning YOU) goofed somewhere"

